function showDualChannelStatus(channel, settings)

fprintf('\n*=========*=====*==============*============*================*==============*==============*================*========*\n');
fprintf(  '| Channel | PRN | L1 Frequency | L1 Doppler | L1 Code Offset | L5 Frequency |  L5 Doppler  | L5 Code Offset | Status |\n');
fprintf(  '*=========*=====*==============*============*================*==============*==============*================*========*\n');

for channelNr = 1 : length(channel)
    if (channel(channelNr).statusL1 ~= '-' && channel(channelNr).statusL5 ~= '-')
        fprintf('|      %2d | %3d |  %+2.4e |    %5.0f   |     %6d     |  %+2.4e |    %5.0f     |    %6d      |     %1s  |\n', ...
                channelNr, ...
                channel(channelNr).PRN, ...
                channel(channelNr).acquiredFreqL1, ...
                channel(channelNr).acquiredFreqL1 - settings.IF1, ...
                channel(channelNr).codePhaseL1, ...
                channel(channelNr).acquiredFreqL5, ...
                channel(channelNr).acquiredFreqL5 - settings.IF5, ...
                channel(channelNr).codePhaseL5, ...
                channel(channelNr).statusL1);
    else
        fprintf('|      %2d | --- |  ------------ |   -----   |    ------   |  ------------ |   -----   |    ------   |   Off  |\n', ...
                channelNr);
    end
end

fprintf('*=========*=====*==============*============*================*==============*==============*================*========*\n\n');
